### ISSUE TITLE
With clean_urls = false, the generated url for preprocessed files has the extension of the page_file

### ISSUE THREAD

**Issue by laumann** [PataphysicalSociety/soupault#44]
I have these settings in `soupault.toml`

```toml
[settings]
  clean_urls = false
[preprocessors]
  md = "cmark --unsafe --smart"
```

and a `foo.md` in my site folder.

```
$ soupault --index-only --dump-index-json index.json
$ cat index.json
[
  {
    "url": "/foo.md",
    "page_file": "site/foo.md",
    "nav_path": []
  }
]
```
I would expect the the `url` to be `/foo.html`, not `foo.md`.

**EDTI**
OS: Linux (Gentoo)
Version: 4.0.0 (the binary distribution downloaded from website, not built from source)
