### ISSUE TITLE
Insert generated index's html in a file other than an index.html

### ISSUE THREAD

**Issue by jyssh** [PataphysicalSociety/soupault#64]
The manual says:

> Soupault can insert HTML rendered from site metadata into the site index pages. By default those are pages named index.*. 

I want to insert this generated index HTML into a `writings.html` file (not named index.html), with `clean_urls=true`. So final location would be`writings.html -> writings/index.html` in build dir.

Currently, soupault, with the following configuration, does not insert the index html into `writings.html`.

```html
<!-- Contents of site/writings.html -->

<ul class="all-posts"></ul>
```

```toml
# index config in soupault.toml

[index.views.all-posts-list]
include_subsections = true
index_selector = "ul.all-posts"
index_item_template = """
  <li>
    <a href="{{url}}" class="font-weight:600">{{title}}</a>
    <p class="margin-block-start:2px font-size:0.9em">Published: <time datetime="{{timestamp}}">{{date}}</time></p>
  </li>
  """
```

Is there a simple configuration I am missing? Do I need to go the [lua index processor route](https://soupault.app/reference-manual/#lua-index-processor)?
